### ISSUE TITLE
Error during failsafe response: No route matches {:action=>"index"}

### ISSUE THREAD

**Issue by jgoodall628** [mirego/gaffe#36]
For some reason none of my custom error pages are not rendering. I have tested everything with blank views and still get this error. When I delete the Gaffe initializer the standard rails 404 pages are rendered properly so it has to do with Gaffe. Here is the terminal output:

```
Started GET "/fadsjklfdsaj" for ::1 at 2016-05-04 09:54:23 -0500
  ActiveRecord::SchemaMigration Load (0.8ms)  SELECT "schema_migrations".* FROM "schema_migrations"

ActionController::RoutingError (No route matches [GET] "/fadsjklfdsaj"):
  actionpack (4.2.0) lib/action_dispatch/middleware/debug_exceptions.rb:21:in `call'
  newrelic_rpm (3.14.0.305) lib/new_relic/agent/instrumentation/middleware_tracing.rb:78:in `call'
  web-console (2.2.1) lib/web_console/middleware.rb:39:in `call'
  newrelic_rpm (3.14.0.305) lib/new_relic/agent/instrumentation/middleware_tracing.rb:78:in `call'
  actionpack (4.2.0) lib/action_dispatch/middleware/show_exceptions.rb:30:in `call'
  newrelic_rpm (3.14.0.305) lib/new_relic/agent/instrumentation/middleware_tracing.rb:78:in `call'
  railties (4.2.0) lib/rails/rack/logger.rb:38:in `call_app'
  railties (4.2.0) lib/rails/rack/logger.rb:20:in `block in call'
  activesupport (4.2.0) lib/active_support/tagged_logging.rb:68:in `block in tagged'
  activesupport (4.2.0) lib/active_support/tagged_logging.rb:26:in `tagged'
  activesupport (4.2.0) lib/active_support/tagged_logging.rb:68:in `tagged'
  railties (4.2.0) lib/rails/rack/logger.rb:20:in `call'
  newrelic_rpm (3.14.0.305) lib/new_relic/agent/instrumentation/middleware_tracing.rb:78:in `call'
  actionpack (4.2.0) lib/action_dispatch/middleware/request_id.rb:21:in `call'
  newrelic_rpm (3.14.0.305) lib/new_relic/agent/instrumentation/middleware_tracing.rb:78:in `call'
  rack (1.6.0) lib/rack/methodoverride.rb:22:in `call'
  newrelic_rpm (3.14.0.305) lib/new_relic/agent/instrumentation/middleware_tracing.rb:78:in `call'
  rack (1.6.0) lib/rack/runtime.rb:18:in `call'
  newrelic_rpm (3.14.0.305) lib/new_relic/agent/instrumentation/middleware_tracing.rb:78:in `call'
  activesupport (4.2.0) lib/active_support/cache/strategy/local_cache_middleware.rb:28:in `call'
  newrelic_rpm (3.14.0.305) lib/new_relic/agent/instrumentation/middleware_tracing.rb:78:in `call'
  rack (1.6.0) lib/rack/lock.rb:17:in `call'
  newrelic_rpm (3.14.0.305) lib/new_relic/agent/instrumentation/middleware_tracing.rb:78:in `call'
  actionpack (4.2.0) lib/action_dispatch/middleware/static.rb:113:in `call'
  newrelic_rpm (3.14.0.305) lib/new_relic/agent/instrumentation/middleware_tracing.rb:78:in `call'
  rack (1.6.0) lib/rack/sendfile.rb:113:in `call'
  newrelic_rpm (3.14.0.305) lib/new_relic/agent/instrumentation/middleware_tracing.rb:78:in `call'
  airbrake (4.3.3) lib/airbrake/user_informer.rb:16:in `_call'
  airbrake (4.3.3) lib/airbrake/user_informer.rb:12:in `call'
  newrelic_rpm (3.14.0.305) lib/new_relic/agent/instrumentation/middleware_tracing.rb:78:in `call'
  railties (4.2.0) lib/rails/engine.rb:518:in `call'
  railties (4.2.0) lib/rails/application.rb:164:in `call'
  newrelic_rpm (3.14.0.305) lib/new_relic/agent/instrumentation/middleware_tracing.rb:78:in `call'
  rack (1.6.0) lib/rack/content_length.rb:15:in `call'
  puma (2.14.0) lib/puma/server.rb:541:in `handle_request'
  puma (2.14.0) lib/puma/server.rb:388:in `process_client'
  puma (2.14.0) lib/puma/server.rb:270:in `block in run'
  puma (2.14.0) lib/puma/thread_pool.rb:106:in `call'
  puma (2.14.0) lib/puma/thread_pool.rb:106:in `block in spawn_thread'


Processing by ErrorsController#show as HTML
Completed 500 Internal Server Error in 9ms
Error during failsafe response: No route matches {:action=>"index"}
  /Users/jeffreygoodall/.rvm/gems/ruby-2.2.1/gems/actionpack-4.2.0/lib/action_dispatch/journey/formatter.rb:46:in `generate'
  /Users/jeffreygoodall/.rvm/gems/ruby-2.2.1/gems/actionpack-4.2.0/lib/action_dispatch/routing/route_set.rb:710:in `generate'
  /Users/jeffreygoodall/.rvm/gems/ruby-2.2.1/gems/actionpack-4.2.0/lib/action_dispatch/routing/route_set.rb:741:in `generate'
  /Users/jeffreygoodall/.rvm/gems/ruby-2.2.1/gems/actionpack-4.2.0/lib/action_dispatch/routing/route_set.rb:784:in `url_for'
  /Users/jeffreygoodall/.rvm/gems/ruby-2.2.1/gems/actionpack-4.2.0/lib/action_dispatch/routing/url_for.rb:156:in `url_for'
  /Users/jeffreygoodall/.rvm/gems/ruby-2.2.1/gems/auto-session-timeout-0.9.2/lib/auto_session_timeout.rb:14:in `block in auto_session_timeout'
  /Users/jeffreygoodall/.rvm/gems/ruby-2.2.1/gems/activesupport-4.2.0/lib/active_support/callbacks.rb:443:in `instance_exec'
  /Users/jeffreygoodall/.rvm/gems/ruby-2.2.1/gems/activesupport-4.2.0/lib/active_support/callbacks.rb:443:in `block in make_lambda'
  /Users/jeffreygoodall/.rvm/gems/ruby-2.2.1/gems/activesupport-4.2.0/lib/active_support/callbacks.rb:163:in `call'
  /Users/jeffreygoodall/.rvm/gems/ruby-2.2.1/gems/activesupport-4.2.0/lib/active_support/callbacks.rb:163:in `block in halting'
  /Users/jeffreygoodall/.rvm/gems/ruby-2.2.1/gems/activesupport-4.2.0/lib/active_support/callbacks.rb:169:in `call'
  /Users/jeffreygoodall/.rvm/gems/ruby-2.2.1/gems/activesupport-4.2.0/lib/active_support/callbacks.rb:169:in `block in halting'
  /Users/jeffreygoodall/.rvm/gems/ruby-2.2.1/gems/activesupport-4.2.0/lib/active_support/callbacks.rb:92:in `call'
  /Users/jeffreygoodall/.rvm/gems/ruby-2.2.1/gems/activesupport-4.2.0/lib/active_support/callbacks.rb:92:in `_run_callbacks'
  /Users/jeffreygoodall/.rvm/gems/ruby-2.2.1/gems/activesupport-4.2.0/lib/active_support/callbacks.rb:734:in `_run_process_action_callbacks'
  /Users/jeffreygoodall/.rvm/gems/ruby-2.2.1/gems/activesupport-4.2.0/lib/active_support/callbacks.rb:81:in `run_callbacks'
  /Users/jeffreygoodall/.rvm/gems/ruby-2.2.1/gems/actionpack-4.2.0/lib/abstract_controller/callbacks.rb:19:in `process_action'
  /Users/jeffreygoodall/.rvm/gems/ruby-2.2.1/gems/actionpack-4.2.0/lib/action_controller/metal/rescue.rb:29:in `process_action'
  /Users/jeffreygoodall/.rvm/gems/ruby-2.2.1/gems/actionpack-4.2.0/lib/action_controller/metal/instrumentation.rb:31:in `block in process_action'
  /Users/jeffreygoodall/.rvm/gems/ruby-2.2.1/gems/activesupport-4.2.0/lib/active_support/notifications.rb:164:in `block in instrument'
  /Users/jeffreygoodall/.rvm/gems/ruby-2.2.1/gems/activesupport-4.2.0/lib/active_support/notifications/instrumenter.rb:20:in `instrument'
  /Users/jeffreygoodall/.rvm/gems/ruby-2.2.1/gems/activesupport-4.2.0/lib/active_support/notifications.rb:164:in `instrument'
  /Users/jeffreygoodall/.rvm/gems/ruby-2.2.1/gems/actionpack-4.2.0/lib/action_controller/metal/instrumentation.rb:30:in `process_action'
  /Users/jeffreygoodall/.rvm/gems/ruby-2.2.1/gems/actionpack-4.2.0/lib/action_controller/metal/params_wrapper.rb:250:in `process_action'
  /Users/jeffreygoodall/.rvm/gems/ruby-2.2.1/gems/activerecord-4.2.0/lib/active_record/railties/controller_runtime.rb:18:in `process_action'
  /Users/jeffreygoodall/.rvm/gems/ruby-2.2.1/gems/actionpack-4.2.0/lib/abstract_controller/base.rb:137:in `process'
  /Users/jeffreygoodall/.rvm/gems/ruby-2.2.1/gems/actionview-4.2.0/lib/action_view/rendering.rb:30:in `process'
  /Users/jeffreygoodall/.rvm/gems/ruby-2.2.1/gems/actionpack-4.2.0/lib/action_controller/metal.rb:195:in `dispatch'
  /Users/jeffreygoodall/.rvm/gems/ruby-2.2.1/gems/actionpack-4.2.0/lib/action_controller/metal/rack_delegation.rb:13:in `dispatch'
  /Users/jeffreygoodall/.rvm/gems/ruby-2.2.1/gems/actionpack-4.2.0/lib/action_controller/metal.rb:236:in `block in action'
  /Users/jeffreygoodall/.rvm/gems/ruby-2.2.1/gems/gaffe-1.0.2/lib/gaffe.rb:29:in `call'
  /Users/jeffreygoodall/.rvm/gems/ruby-2.2.1/gems/gaffe-1.0.2/lib/gaffe.rb:29:in `block in enable!'
  /Users/jeffreygoodall/.rvm/gems/ruby-2.2.1/gems/actionpack-4.2.0/lib/action_dispatch/middleware/show_exceptions.rb:47:in `call'
  /Users/jeffreygoodall/.rvm/gems/ruby-2.2.1/gems/actionpack-4.2.0/lib/action_dispatch/middleware/show_exceptions.rb:47:in `render_exception'
  /Users/jeffreygoodall/.rvm/gems/ruby-2.2.1/gems/actionpack-4.2.0/lib/action_dispatch/middleware/show_exceptions.rb:35:in `rescue in call'
  /Users/jeffreygoodall/.rvm/gems/ruby-2.2.1/gems/actionpack-4.2.0/lib/action_dispatch/middleware/show_exceptions.rb:30:in `call'
  /Users/jeffreygoodall/.rvm/gems/ruby-2.2.1/gems/newrelic_rpm-3.14.0.305/lib/new_relic/agent/instrumentation/middleware_tracing.rb:78:in `call'
  /Users/jeffreygoodall/.rvm/gems/ruby-2.2.1/gems/railties-4.2.0/lib/rails/rack/logger.rb:38:in `call_app'
  /Users/jeffreygoodall/.rvm/gems/ruby-2.2.1/gems/railties-4.2.0/lib/rails/rack/logger.rb:20:in `block in call'
  /Users/jeffreygoodall/.rvm/gems/ruby-2.2.1/gems/activesupport-4.2.0/lib/active_support/tagged_logging.rb:68:in `block in tagged'
  /Users/jeffreygoodall/.rvm/gems/ruby-2.2.1/gems/activesupport-4.2.0/lib/active_support/tagged_logging.rb:26:in `tagged'
  /Users/jeffreygoodall/.rvm/gems/ruby-2.2.1/gems/activesupport-4.2.0/lib/active_support/tagged_logging.rb:68:in `tagged'
  /Users/jeffreygoodall/.rvm/gems/ruby-2.2.1/gems/railties-4.2.0/lib/rails/rack/logger.rb:20:in `call'
  /Users/jeffreygoodall/.rvm/gems/ruby-2.2.1/gems/newrelic_rpm-3.14.0.305/lib/new_relic/agent/instrumentation/middleware_tracing.rb:78:in `call'
  /Users/jeffreygoodall/.rvm/gems/ruby-2.2.1/gems/actionpack-4.2.0/lib/action_dispatch/middleware/request_id.rb:21:in `call'
  /Users/jeffreygoodall/.rvm/gems/ruby-2.2.1/gems/newrelic_rpm-3.14.0.305/lib/new_relic/agent/instrumentation/middleware_tracing.rb:78:in `call'
  /Users/jeffreygoodall/.rvm/gems/ruby-2.2.1/gems/rack-1.6.0/lib/rack/methodoverride.rb:22:in `call'
  /Users/jeffreygoodall/.rvm/gems/ruby-2.2.1/gems/newrelic_rpm-3.14.0.305/lib/new_relic/agent/instrumentation/middleware_tracing.rb:78:in `call'
  /Users/jeffreygoodall/.rvm/gems/ruby-2.2.1/gems/rack-1.6.0/lib/rack/runtime.rb:18:in `call'
  /Users/jeffreygoodall/.rvm/gems/ruby-2.2.1/gems/newrelic_rpm-3.14.0.305/lib/new_relic/agent/instrumentation/middleware_tracing.rb:78:in `call'
  /Users/jeffreygoodall/.rvm/gems/ruby-2.2.1/gems/activesupport-4.2.0/lib/active_support/cache/strategy/local_cache_middleware.rb:28:in `call'
  /Users/jeffreygoodall/.rvm/gems/ruby-2.2.1/gems/newrelic_rpm-3.14.0.305/lib/new_relic/agent/instrumentation/middleware_tracing.rb:78:in `call'
  /Users/jeffreygoodall/.rvm/gems/ruby-2.2.1/gems/rack-1.6.0/lib/rack/lock.rb:17:in `call'
  /Users/jeffreygoodall/.rvm/gems/ruby-2.2.1/gems/newrelic_rpm-3.14.0.305/lib/new_relic/agent/instrumentation/middleware_tracing.rb:78:in `call'
  /Users/jeffreygoodall/.rvm/gems/ruby-2.2.1/gems/actionpack-4.2.0/lib/action_dispatch/middleware/static.rb:113:in `call'
  /Users/jeffreygoodall/.rvm/gems/ruby-2.2.1/gems/newrelic_rpm-3.14.0.305/lib/new_relic/agent/instrumentation/middleware_tracing.rb:78:in `call'
  /Users/jeffreygoodall/.rvm/gems/ruby-2.2.1/gems/rack-1.6.0/lib/rack/sendfile.rb:113:in `call'
  /Users/jeffreygoodall/.rvm/gems/ruby-2.2.1/gems/newrelic_rpm-3.14.0.305/lib/new_relic/agent/instrumentation/middleware_tracing.rb:78:in `call'
  /Users/jeffreygoodall/.rvm/gems/ruby-2.2.1/gems/airbrake-4.3.3/lib/airbrake/user_informer.rb:16:in `_call'
  /Users/jeffreygoodall/.rvm/gems/ruby-2.2.1/gems/airbrake-4.3.3/lib/airbrake/user_informer.rb:12:in `call'
  /Users/jeffreygoodall/.rvm/gems/ruby-2.2.1/gems/newrelic_rpm-3.14.0.305/lib/new_relic/agent/instrumentation/middleware_tracing.rb:78:in `call'
  /Users/jeffreygoodall/.rvm/gems/ruby-2.2.1/gems/railties-4.2.0/lib/rails/engine.rb:518:in `call'
  /Users/jeffreygoodall/.rvm/gems/ruby-2.2.1/gems/railties-4.2.0/lib/rails/application.rb:164:in `call'
  /Users/jeffreygoodall/.rvm/gems/ruby-2.2.1/gems/newrelic_rpm-3.14.0.305/lib/new_relic/agent/instrumentation/middleware_tracing.rb:78:in `call'
  /Users/jeffreygoodall/.rvm/gems/ruby-2.2.1/gems/rack-1.6.0/lib/rack/content_length.rb:15:in `call'
  /Users/jeffreygoodall/.rvm/gems/ruby-2.2.1/gems/puma-2.14.0/lib/puma/server.rb:541:in `handle_request'
  /Users/jeffreygoodall/.rvm/gems/ruby-2.2.1/gems/puma-2.14.0/lib/puma/server.rb:388:in `process_client'
  /Users/jeffreygoodall/.rvm/gems/ruby-2.2.1/gems/puma-2.14.0/lib/puma/server.rb:270:in `block in run'
  /Users/jeffreygoodall/.rvm/gems/ruby-2.2.1/gems/puma-2.14.0/lib/puma/thread_pool.rb:106:in `call'
  /Users/jeffreygoodall/.rvm/gems/ruby-2.2.1/gems/puma-2.14.0/lib/puma/thread_pool.rb:106:in `block in spawn_thread'
```

**Comment by simonprev** [comment]
Could you paste the content of your initializer and your `ErrorsController` please?

**Comment by jgoodall628** [comment]
class ErrorsController < ApplicationController
  include Gaffe::Errors

  # Make sure anonymous users can see the page
  skip_before_filter :authenticate_user!

  # Override 'error' layout
  layout 'application'

  # Render the correct template based on the exception “standard” code.
  # Eg. For a 404 error, the `errors/not_found` template will be rendered.
  def show
    @use_default_layout = false
    # Here, the `@exception` variable contains the original raised error
    render "errors/#{@rescue_response}", status: @status_code
  end
end


Initalizer:
Gaffe.configure do |config|
  config.errors_controller = 'ErrorsController'
end

Gaffe.enable!

**Comment by remiprev** [comment]
Have you tried to reduce the controller to its minimum? Can you try this `show` action?

```ruby
def show
  render text: 'Gaffe is working!'
end
```

**Comment by jgoodall628** [comment]
Render plain text produces the same error

**Comment by remiprev** [comment]
It raises the exact same _No route matches {:action=>"index"}_ error?

**Comment by jgoodall628** [comment]
So the issue is being caused a gem I have set up called auto_session_timeout. It runs this method in the ApplicationController.

def auto_session_timeout(seconds=nil)
      prepend_before_filter do |c|
        if c.session[:auto_session_expires_at] && c.session[:auto_session_expires_at] < Time.now
          c.send :reset_session
        else
          unless c.request.original_url.start_with?(c.send(:active_url))
            offset = seconds || (current_user.respond_to?(:auto_timeout) ? current_user.auto_timeout : nil)
            c.session[:auto_session_expires_at] = Time.now + offset if offset && offset > 0
          end
        end
      end

Any thoughts on a work around? I do not believe you can skip actions defined in procs.

**Comment by remiprev** [comment]
Indeed, I don’t think you can. You might be better off at either forking the gem and modify it to give this `prepend_before_filter` a method name so you’ll be able to `skip_before_filter` it in your `ErrorsController`.

Another solution would be to have this kind of controller structure:

* `ApplicationController < ActionController::Base`
  * This is the controller that provides common behavior and settings for all controllers
* `Web::ApplicationController < ::ApplicationController`
  * The `auto_session_timeout` would be used in this controller
  * This controller should be the parent of _all_ your controllers that currently inherit from `ApplicationController`, except for `ErrorsController`
* `ErrorsController < ::ApplicationController`
  * This is the error controller used by Gaffe

Both solutions require some work but nothing can be done by Gaffe to circumvent it, sorry!

**Comment by jgoodall628** [comment]
I was able to copy a named version of the problem method into my application controller which worked. Thank you so much for your help!

**Comment by TB-Development** [comment]
> Indeed, I don’t think you can. You might be better off at either forking the gem and modify it to give this `prepend_before_filter` a method name so you’ll be able to `skip_before_filter` it in your `ErrorsController`.
> 
> Another solution would be to have this kind of controller structure:
> 
>     * `ApplicationController < ActionController::Base`
>       
>       * This is the controller that provides common behavior and settings for all controllers

This worked for me.  Replacing

```
class ErrorsController < ApplicationController
```

with 

```
class ErrorsController < ActionController::Base
```

loads the template without errors.  Probably something with what my ApplicationController was doing, worked for me at least.
