### ISSUE TITLE
Gaffe doesnt work when controller inherits from ActionController::API

### ISSUE THREAD

**Issue by tikiboy88** [mirego/gaffe#40]
In the ErrorController class for the API module, my base class extends from ActionController::API instead of ActionController::Base.

Upon starting up rails server, I get the following error (short backtrace):

```
/Users/abc/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/gaffe-1.1.0/lib/gaffe/errors.rb:8:in `block in <module:Errors>': undefined method `layout' for Api::ErrorsController:Class (NoMethodError)
	from /Users/abc/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/activesupport-4.2.4/lib/active_support/concern.rb:120:in `class_eval'
	from /Users/abc/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/activesupport-4.2.4/lib/active_support/concern.rb:120:in `append_features'
	from /Users/abc/Server/RoR/xyz/app/controllers/api/errors_controller.rb:4:in `include'
	from /Users/abc/Server/RoR/xyz/app/controllers/api/errors_controller.rb:4:in `<class:ErrorsController>'
	from /Users/abc/Server/RoR/xyz/app/controllers/api/errors_controller.rb:3:in `<module:Api>'
	from /Users/abc/Server/RoR/xyz/app/controllers/api/errors_controller.rb:2:in `<top (required)>'

```

If i change the inheritance of the ErrorController class to ActionController::Base, then no issues were found and everything worked perfectly. 

I suspect this is due to Gaffe requiring that the "layout" function be present.

**Comment by Alex1sz** [comment]
'+ 1'
